version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - make

jobs:

  make:
    docker:
      - image: didstopia/sdl2
    steps:
      - checkout
      - run: make
      - run: ls -la
      - store_artifacts:
          path: fb
