version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - make

jobs:

  make:
    docker:
      - image: didstopia/sdl2
    steps:
      - checkout
      - run: apt install libmodplug-dev -y
      - run: git clone https://github.com/soundcloud/tremor.git
      - run: cd tremor && ./autogen.sh && make && make install
      - run: make
      - run: ls -la
      - store_artifacts:
          path: fb
